### PR TITLE
Point to new main repo in README

### PR DESCRIPTION
**Pull request by sweetpi**

### CODE REVIEW

**Comment by fabiankrauss** [comment]
Hallo 2. questions,
can I change the set tempature of the max-thermostat?
if yes, how???

**Comment by sweetpi** [comment]
Could you please post all you devices of your config? Check if either the device name is given twice or the plugin is loaded twice.

**Comment by fabiankrauss** [comment]
{
      "plugin": "max-thermostat",
      "host": "192.168.178.35",
      "port": 62910
    },
-------------------------------
    {
      "id": "fenster-badezimmer",
      "class": "MaxContactSensor",
      "name": "Fenster Bad",
      "deviceNo": "0cb03e"
    },
    {
      "id": "heizung-badezimmer",
      "class": "MaxThermostatDevice",
      "name": "Heizung Bad",
      "roomID": 1,
      "deviceNo": "10657d",
      "comfyTemp": 21.5,
      "ecoTemp": 16.5,
      "vacTemp": 16.5,
      "actTemp": 23,
      "mode": "auto",
      "battery": "ok"
    },
    {
      "id": "heizung-wohnzimmer",
      "class": "MaxThermostatDevice",
      "name": "Heizung Wohnzimmer",
      "roomID": 2,
      "deviceNo": "10656d",
      "comfyTemp": 21.5,
      "ecoTemp": 16.5,
      "vacTemp": 16.5,
      "actTemp": 23,
      "mode": "auto",
      "battery": "ok"
    },
    {
      "id": "heizung-arbeitszimmer",
      "class": "MaxThermostatDevice",
      "name": "Heizung Arbeitszimmer",
      "roomID": 3,
      "deviceNo": "1065b8",
      "comfyTemp": 21.5,
      "ecoTemp": 16.5,
      "vacTemp": 16.5,
      "actTemp": 23.5,
      "mode": "auto",
      "battery": "ok"
    },

It doesn´t work with anyone of these devices.
The plugin is version 0.8.1.
Could the problem be, that the MAX! Cube control the Thermostat too?
For example, if I open the "BadFenster" the temp of the Thermostate will be set to 12C°.
If this is the problem, how can I solve it?

**Comment by georg90** [comment]
Only one Software can connect to the cube, so e.g. you have the Max! Software open while trying to connect to it via pimatic it won't work. (restart the cube if you're not sure)
Your config look ok

**Comment by fabiankrauss** [comment]
How can I stop the Max! Software? This could be the problem!

**Comment by georg90** [comment]
It's running on your Computer - just Close the application (or for testing) shutdown your Computer, restart the cube and try again

**Comment by fabiankrauss** [comment]
I shutted down my Computer, turned the voltage off of the cube, have waited 2 minutes, turned the voltage on. Now it still don´t work. :(

**Comment by georg90** [comment]
maybe your cube is working with a different port..
My knowledge Ends here :-/ 
sorry!

**Comment by sweetpi** [comment]
> {
>   "plugin": "max-thermostat",
>   "host": "192.168.178.35",
>   "port": 62910
> },

This is the name for the old plugin. Use:

```
{
  "plugin": "max-thermostat",
  "host": "192.168.178.35",
  "port": 62910
},
```

Also the device config change, please use the example from: https://github.com/pimatic/pimatic-max

@georg90: Could you merge this pull request? To make sure people see that the name changed and use the new README.

**Comment by fabiankrauss** [comment]
Can I only change the name from plugin:"max-thermostat"  to "max"
and the class from "MaxThermostatDevice" to "MaxHeatingThermostat" ? Is this enough or have I to change something else. Sorry for my bad english

**Comment by sweetpi** [comment]
`deviceNo` was renamed to `rfAddress` and some useless config entries removed.

**Comment by leader21** [comment]
> How can I stop the Max! Software?

check the taskbar for the max! symbol. max

try to click right mouse button and close it. maybe this helps. 
there's also an app for mobile phones. here it's the same - there can only be one connection to the cube. if you use it, close it and make sure via memory manager that it's not running in the background anymore.

**Comment by georg90** [comment]
@sweetpi 
You're right - I got confused with this old repo as well :-/

**Pull request merged**
